version: "3.9"
services:
    haproxy:
        image: haproxy:2.7
        volumes:
            - ./haproxy:/haproxy-override
            - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
            - /etc/letsencrypt/live/ha.coulombel.net:/certs
        ports:
            - "80:80"
            - 443:443
            - "70:70" # haproxy admin console, login with user:pass